### ISSUE TITLE
local news and local news thumbnail image size 

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#118]
Currently the handlebars template for local news and events is using the img_url of the asset thumbnail. 

This is causing the thumbnail variety to repeat on the hero images. 

![thumbnail-size-repeat](https://cloud.githubusercontent.com/assets/1305804/15530812/f33767d8-2299-11e6-95a4-0c107a250afc.png)

So we should just be able to select the main image, then the correct variety is used where needed.

![setting-thumbnail-image](https://cloud.githubusercontent.com/assets/1305804/15530810/f3365fb4-2299-11e6-9c4d-88878c0a961c.png)

Need to add some conditions to pull out the correct variety size based on needs.

Thumbnail:

![thumb-size](https://cloud.githubusercontent.com/assets/1305804/15530814/f3378ccc-2299-11e6-8244-36810fd5d986.png)

Medium: 

![medium-size](https://cloud.githubusercontent.com/assets/1305804/15530813/f3377296-2299-11e6-8461-7f09f57a746a.png)

Original: 

![orginal-image-asset large](https://cloud.githubusercontent.com/assets/1305804/15530811/f3376396-2299-11e6-9bf3-b2bc1c0db7de.png)

**Comment by yevek** [comment]
Also the size of the images seem to affect the way the line up. 

![local-news-event-hero](https://cloud.githubusercontent.com/assets/1305804/15531260/c48bb300-229c-11e6-9655-758930c54de3.png)

**Comment by dkevey** [comment]
can't find this example think it was fixed in v3
