### ISSUE TITLE
gallery component - display static images from a folder

### ISSUE THREAD

**Issue by siftnoorsingh** [unimelb/matrix-controlled-environment#140]
I wish to display the sponsor images in this format:

<img width="1421" alt="screen shot 2016-07-05 at 12 04 42 pm" src="https://cloud.githubusercontent.com/assets/13805518/16572216/8a729490-42a9-11e6-91b2-b9feaf886acf.png">

And I do not wish to use gallery component for this as I want the images to be displayed in equally sized boxes, rather than based on the original size of the image. All the logo images have been placed in a folder. But when I try to import that folder into the listings component in Matrix, it throws the following error:

<img width="868" alt="screen shot 2016-07-05 at 12 04 30 pm" src="https://cloud.githubusercontent.com/assets/13805518/16572243/d906e87c-42a9-11e6-9f40-5ff2259e925c.png">

And a hardcoded listing component has to be created in order to get the logos as a listing. Is there a way that the listing component could be modified so that it accepts a folder containing images and displays them in a listing format?

**Comment by yevek** [comment]
This option would work best in the gallery component as we could easily add a new style. Waiting for style to get added to design system

![gallery-layout](https://cloud.githubusercontent.com/assets/1305804/17580506/72a4ca58-5fe2-11e6-8a3e-eafeb856f476.png)

**Comment by dkevey** [comment]
Image listing has been created https://resources.web.unimelb.edu.au/controlled-environment/content-templates/image-listing woohoo!
