### ISSUE TITLE
Sharing events from a feed

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#151]
Problem encountered by Law (and others) using events/news sourced from a feed.

Sharing options for URLs such as http://law.unimelb.edu.au/events/detail?event=7106 produce a very generic preview.

![screen shot 2016-08-01 at 11 48 50 am](https://cloud.githubusercontent.com/assets/848310/17281213/f8194dd8-57dd-11e6-80b3-6ea37ac598c1.png)

Unfortunately, the result is not much better when sharing the direct URL (if one is available) - it still doesn't pick up the images associated with the event.

![screen shot 2016-08-01 at 11 50 40 am](https://cloud.githubusercontent.com/assets/848310/17281238/3d108f0a-57de-11e6-9fd1-39ead70347e2.png)

A solution would be to first diagnose, and if necessary, fix the events feed to supply an image in a predictable manner, then use some smart keywords to detect the appropriate heading/description/image presence in the feed and generate the necessary metadata dynamically.

**Comment by tomstringer** [comment]
Andrew, in the new version of this we've now got microdata on titles, presenters etc. That should help a bit with images. 

The title's a little tricker because it's always the same page. We can change the title and description with Javascript, but not sure that will help with search?

**Comment by yevek** [comment]
I think we should get events.unimelb to be fixed so that "non-featured" events are previewed from events.unimelb instead of from the CMS. I'll follow up with Neil about this.

**Comment by yevek** [comment]
events.unimelb has been updated to new template - investigate next steps.

**Comment by dkevey** [comment]
closing this one as this is similar to #291 and should be refactored to go directly to events.unimelb
