### ISSUE TITLE
In-tab component does not work with Tab component

### ISSUE THREAD

**Issue by namgupta** [unimelb/matrix-controlled-environment#154]
A page with in-tab navigation does not work with a tab component. This causes the tab component to display nothing until it is clicked on. The tab containing the in tab nav does not display in-tab headings.

**Comment by yevek** [comment]
Design Team mentioned that these 2 components weren't designed to work together, marking as won't fix.

**Comment by angehb** [comment]
Can I ask why does FBE have it working.  Refer attached.
![fbe-navigation](https://cloud.githubusercontent.com/assets/21251734/17990269/7cd51d52-6b77-11e6-91fb-ea2037e0c29c.JPG)

**Comment by tomstringer** [comment]
@angehb FBE has created a custom javascript-based page, essentially over-riding the design system. They are outside the Matrix Controlled Environment and as such, are not supported by the central digital team.

If you're looking for an on-page filtering function for news and events, I'd suggest that would be a new feature request. The way FBE have implemented their page is against the advice of our designers (as @yevek mentioned).

**Comment by tomstringer** [comment]
I haven't tested this yet, but my understanding is v5 of the design system (applied to MCE this morning) should now allow this.
