### ISSUE TITLE
Combined listing - caching issues

### ISSUE THREAD

**Issue by tomstringer** [unimelb/matrix-controlled-environment#170]
When new local events/news items get added to the sourceLocations, it takes some time for these to appear in the feed, as there are a number of assets that need to be recached.

Have submitted a ticket to Squiz to see if there's a way we can set a complex trigger to detect when this occurs and to clear the relevant feed asset (see Squiz ticket: 104791)

@yevek @cigar69

**Comment by tomstringer** [comment]
@FPG-Github Has been working on a fix for this.

**Comment by yevek** [comment]
following up the completed Squiz ticket for this one https://my.squiz.net/#/support/ticket-detail/104791
