### ISSUE TITLE
News and events component - no parent asset selected

### ISSUE THREAD

**Issue by spacetj** [unimelb/matrix-controlled-environment#189]
When there are no news items to display, the new component (News or Events Listing) says "No Parent Asset selected". Which makes it sounds as though the webpage is broken.

While the old component says "No current news items". 
![screen shot 2016-10-03 at 3 50 55 pm](https://cloud.githubusercontent.com/assets/12206849/19028037/1ebc099a-8983-11e6-9bd7-a963414d4ce2.png)

**Comment by tomstringer** [comment]
@spacetj Can you give us the link of the page you were trying to do this on?

**Comment by spacetj** [comment]
@tomstringer http://law.unimelb.edu.au/news/the-tax-group/_nocache

There are no news items under this parent asset. But instead of the webpage saying there are no items, it sounds as though the webpage is broken. Maybe it should have a different error message for when no news items are present under the parent asset.

**Comment by dkevey** [comment]
I updated this message to say "There are no current news items to display" and if a root not hasn't been selected the error is only displayed to editors - not public.
