### ISSUE TITLE
Calendar paint layout detect email or phone number

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#193]
Would be good to be able to detect if email or phone number is used and adjust "T" or "E" in front of contact. 

![detect if email or phone](https://cloud.githubusercontent.com/assets/1305804/19500125/2eec538c-95e6-11e6-9d38-ced9ac4df336.png)

**Comment by FPG-Github** [comment]
Easiest would be to just remove the T or E reference - a bit redundant as it is obvious if it is a phone or email? 

Otherwise parse the input to search for the @ symbol - assumption that if you find it then it is an email, else it is a phone number...

**Comment by dkevey** [comment]
removed T to fix this issue
