### ISSUE TITLE
Single Calendar event end date problem

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#218]
Jessica Taylor notes:
"A second issue is that when a start time is entered for an event but no finish time, the event displays an arbitrary finish time. See: 
http://mdhs.unimelb.edu.au/engage/alumni/events-and-reunions/melbourne-medical-school-class-of-1962-reunion/_nocache 
This event starts at 12pm with no end date enabled but shows it goes until 9.59am."

Why it chooses 9:59 is [long and complicated](https://unimelbit.zendesk.com/agent/tickets/6471), but the bottom line is that if a user doesn't enter an end time on an event, the paint layout still tries to display an end time.

Just need to add an extra if statement to the display of the end time keywords.

![screen shot 2016-12-14 at 2 38 48 pm](https://cloud.githubusercontent.com/assets/848310/21168842/4f8b1f46-c20b-11e6-9a6c-be723ad5ec4d.png)
![screen shot 2016-12-14 at 2 38 20 pm](https://cloud.githubusercontent.com/assets/848310/21168843/4f8ec10a-c20b-11e6-94ce-5828588933e4.png)

**Comment by dkevey** [comment]
Have fixed this to remove not show if end datetime equals 9:59am. It's a bit of a hack, but works ok for now.
