### ISSUE TITLE
& (Ampersand) in News/Event names not displaying

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#223]
Ampersand characters are being output as `&amp;` in both news item and event blocks, across multiple platforms: MCE, Bespoke
May be issues with other special characters.

Screenshot
MCE event: 
![image](https://cloud.githubusercontent.com/assets/15081925/22042364/f01662d6-dd5e-11e6-8aaf-187c34aec999.png)
(Using combined News & Events listing v3)

Was located here: http://students.fvas.unimelb.edu.au/_recache#news-events
Ampersand in name has since been changed to "and" to avoid issue

Bespoke news item: 
![image](https://cloud.githubusercontent.com/assets/15081925/22042378/fcad0ad6-dd5e-11e6-9d0a-a09c0e1f7989.png)
Located at: http://www.fvas.unimelb.edu.au/#news (May have been fixed)

**Comment by dkevey** [comment]
I think I've fixed this one in MCE so closing off
