### ISSUE TITLE
News or Events Listing content template "past events" option listing current events

### ISSUE THREAD

**Issue by FPG-Github** [unimelb/matrix-controlled-environment#224]
When using the  "past events" option in the News or Events Listing content template with multi-day calendar events, it will list currently running events as past events because the start date has past. 

The following screen shot was taken on 18 Jan 2017, so all events are still current but the start day has past so they are being listed as past events:
![past events listing issues](https://cloud.githubusercontent.com/assets/4566277/22050057/be656d04-dd8b-11e6-8b6d-b3ed8c3b2895.PNG)

Possible solution is to wrap the current Default Format (Id: #2080780) results code generated by the Past events (Id: #2080778) search in a option statement that checks if the end date has past yet so that only events whose end date is past will be printed, current event will be skipped - i.e.:
  %begin_event_end_datetime has past%. 
           Current code block
  %end_event_end_datetime has past%.

**Comment by gyounger** [comment]
thanks for posting this one and potential solution

**Comment by dkevey** [comment]
fixed this in new Events listing content template https://resources.web.unimelb.edu.au/controlled-environment/content-templates/events-listing no further action required
