### ISSUE TITLE
og:image tag not showing on Standard Page Asset

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#225]
URL: http://arts.unimelb.edu.au/the-policy-lab

<meta property="og:image"> tag not set on Standard Page of new website. Looks like the image being used is a cached image of their old website.

Unsure how we currently set the og:image (or should) but is it possible to set the default to the thumbnail of the Standard Page?

Cheers,

jporich (james.porich@unimelb.edu.au)

**Comment by dkevey** [comment]
will chat with the team about this and whether we use the thumbnail or banner image @woowoowoo any thoughts? I'm thinking thumbnail as it allows for additional image that could remain static vs the banner that changes or is not present?

**Comment by jporich** [comment]
Hi guys,

Just thought I'd note that apparently the <meta property="og:image"> if not set is apparently going to search for the first available set of <img /> tags and present those as the options.

So for example http://arts.unimelb.edu.au/ when put in to Facebook attaches the following image to the post (see attachment) note: apparently Facebook has it's own crawler hence why the image can't be found (caching) - but the image on this page appears first on the **Events** section on the website - two tabs over from the landing page.

As the banner is a background image and the unimelb logo is an svg Facebook will ignore these :( - just thought I'd mention that in case there were any sort of considerations around fallbacks in case no thumbnail is set.

<img width="505" alt="screen shot 2017-01-20 at 9 21 43 am" src="https://cloud.githubusercontent.com/assets/10070570/22127948/606b5462-def2-11e6-8400-e782f06d6e70.png">

**Comment by dkevey** [comment]
ok - so turns out we have the og:image tag available but it only shows if you set a thumbnail on that page - can you add a thumbnail to http://arts.unimelb.edu.au/the-policy-lab and confirm that it works?

![image](https://cloud.githubusercontent.com/assets/1305804/22128062/f186a8c0-def2-11e6-998f-3fdb9db243b9.png)

**Comment by jporich** [comment]
Hi Donna,

Seems that I'm getting no image showing for http://arts.unimelb.edu.au/the-policy-lab

I've set the thumbnail - and the <meta property="og:image" content="%thumbnail%"> _IS_ showing in the source code, however interestingly it isn't showing up in Facebook.

I'm running the page through https://developers.facebook.com/tools/debug/ and I'm getting a few errors specifically related to og:image ? 😮 

See attached screen shot.

- **Inferred Property** The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
- **Share App ID Missing** The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
- **Inferred Property** The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

Bit odd as the tag _is_ explicitly provided. 

**NOTE:** just told Facebook to do another scrape and now it seems to detect the og:image tag. But now we have a new issue 😭 

- **Image unavailable** Provided og:image, http://arts.unimelb.edu.au/__data/assets/image/0010/2235493/policy-lab-logo.png could not be downloaded because it exceeded the maximum allowed sized of 8Mb or your server was too slow to respond.

<img width="1440" alt="screen shot 2017-01-20 at 10 12 49 am" src="https://cloud.githubusercontent.com/assets/10070570/22129321/5af6827a-def9-11e6-9b0f-3b08345723d4.png">

**Comment by dkevey** [comment]
The only error that I am getting is that we don't have the **fb:app_id** property (which we don't have on the page) - do you have a fb:app_id that I can test with? - the rest looks ok to me. 

![image](https://cloud.githubusercontent.com/assets/1305804/22129606/2855969c-defb-11e6-9643-9280db826116.png)

**Comment by jporich** [comment]
Interesting!

Seems to be working now - looks like it's down to Facebooks scraping and caching. Will make note for future.

No app_id unfortunately - think I might have an old one kicking around somewhere. Testedd on mobile in Facebooks app and also seems to link fine :)

Thanks for that one @dkevey ^.^

**Comment by dkevey** [comment]
added in comment to indicate that thumbnail image should be set
<img width="1025" alt="thumbnail" src="https://cloud.githubusercontent.com/assets/1305804/22269035/d2406822-e2dd-11e6-8a6a-ef39f149a6a9.png">
