### ISSUE TITLE
News OR Events Container Template to show assets of type "Link"

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#226]
Request:
News OR Events Container Template to show assets of type "Link", just like the combined listing.

This is useful for people to have blocks that link to external sites such as ABC news, pursuit etc.

**Comment by dkevey** [comment]
Definitely need to have this available.

**Comment by dkevey** [comment]
finally added this in - actually thought I'd already completed this now. Link asset works in News listing. Updated instructions here: https://resources.web.unimelb.edu.au/controlled-environment/content-templates/news-events
