### ISSUE TITLE
More ordering options for filtered listing page templates

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#228]
For the page templates that use the filtered listing:
-Filtered Listing page
-Filtered Listing course page
-Filtered Listing project page

Currently the only ordering option is "alphabetically"

It would be extremely useful to be able to order in a number of other ways, including:
-Down the tree (asset tree manual ordering)
-Current first, then past (for projects)
-By colour code, so all colours are together, rather than mixed

Stakeholder would very much like to have current projects first, then past (completed) projects. The second-level ordering (after current/past) would be alphabetical.

See image for ugly-looking out-of-order listing:
![research-projects-listing-order](https://cloud.githubusercontent.com/assets/15081925/22190356/de9b3d1c-e176-11e6-998e-1a40d62465db.PNG)

**Comment by dkevey** [comment]
yep got this one already #98
