### ISSUE TITLE
Move download icons to the LEFT of link text to align them in file listings

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#229]
When using automated file listing components such as the "Resources" sidebar (aside content), the download icons are currently printing after the links, causing them to look very messy due to them not aligning.
See example:
![icons-out-of-alignment](https://cloud.githubusercontent.com/assets/15081925/22234358/a3d87534-e24b-11e6-81a8-3be2ec3f344f.PNG)
On this page: https://staff.unimelb.edu.au/students-teaching/academic-board/committees/talqac/_nocache

It would be much better to put the download icon first, before the link text, so that the icons line up when used as lists. It looks much better and more professional. See this example:
![icons-in-alignment](https://cloud.githubusercontent.com/assets/15081925/22234373/d11a1994-e24b-11e6-94c1-89c2d2136a7b.PNG)
On this page: http://ssip.staff.unimelb.edu.au/#briefings

**Comment by dkevey** [comment]
Hi @rhyslawry I actually think the download icons look best after the text. It's easier when scanning the page to read the text first. The icon is just supplementary to indicate to user what action will be taken clicking on the hyperlink.

In the Staff Hub example - it looks like those documents need to be named correctly (rather than just the file name). I also don't think it's necessary to include the file size unless it's huge.

**Comment by rhyslawry** [comment]
@dkevey 
Hey Donna,
The problem is actually with the Staff Hub template
That file listing is automated, so I have no control over whether it displays the file size/type - I would prefer it not to display the file size as well.
(the one you get when you add a resources folder in Staff Hub)

I personally think it's easier to read if the icon is first. The text lines up either way so people's eyes are automatically drawn to the words.
If the icon is on the left, both the icon and the text will line up.
If the icon is last, only the text lines up, the icon doesn't.

I agree with you that the icon should be on the right for _in-line_ document download links though.

**Comment by dkevey** [comment]
RE: the Staff Hub template - should be able to put some conditional statement in the template to only show a file size above a certain size. This feedback should go to Staff Hub team staff-hub@unimelb.edu.au as they are re-doing templates. 

The other issue about alignment is a Design issue and should be logged on https://github.com/unimelb/unimelb-design-system/issues (sorry it's confusing having two, and not able to push to other repo)
