### ISSUE TITLE
Introductory text for listings only, not for lead text

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#231]
Is it possible to add a checkbox option to make the Introductory Text metadata field not show on the page? Alternatively to separate out Introductory text and 'Listing Text' functionality so that you can have one without the other?

We want to have a short description visible for the Listing Content Templates - however we do not wish to have a large <p class="lead"> at the beginning of pages.

**Comment by dkevey** [comment]
Yes I think I could add in an override for that - do you have some example URLs?

**Comment by jporich** [comment]
This page 

http://arts.unimelb.edu.au/engage

Features "Extended and Community Learning Programs" (currently using a redirect page 2248728 to simulate)

**Comment by dkevey** [comment]
@jporich after reviewing how this field is currently used throughout MCE - we are inclined to keep it as it is at this stage. The majority of pages that I've viewed are using this field correctly and consistently. In this instance above the intro text is a tad bit long - but still acceptable (in my opinion).
![image](https://user-images.githubusercontent.com/1305804/28654880-0914bd84-72db-11e7-96c2-fb21150417f9.png)

However, we have noted that for the upcoming rebranded DDS that we will not be implementing this on page templates.

In this example, I'm more concerned that the child pages are using the home page template on 3rd/4th level pages - and there is no clear navigation back to the main section.
http://arts.unimelb.edu.au/engage/international-engagement
http://arts.unimelb.edu.au/engage/international-engagement/faculty-of-arts-indonesia-initiative

![image](https://user-images.githubusercontent.com/1305804/28654933-704251c4-72db-11e7-8409-1b877b376506.png)

I'm going to mark this request for future consideration, but close it from the current MCE issues.
