### ISSUE TITLE
Update Listing content template to work correctly with Redirect assets  

### ISSUE THREAD

**Issue by FPG-Github** [unimelb/matrix-controlled-environment#233]
The Listing Content Template works fine with link assets for listing Link Assets under a parent, but fails to load the Introductory text for Redirect assets - so setting up a link and redirect asset with the same information has different results.
![test listing template](https://cloud.githubusercontent.com/assets/4566277/22671287/b2f073d8-ed21-11e6-8636-4c7e73dac1ce.PNG)

 Either need to remove the Redirect Assert as an option or update it to include the Intro Text.

**Comment by dkevey** [comment]
Have fixed this to work with redirect page asset. 

- Updated instructions to include asset types
- Add page to show all listing examples: https://resources.web.unimelb.edu.au/controlled-environment/content-templates/listing/options/listing-component-options
