### ISSUE TITLE
V3 Combined news And events feed shows blank if eventTags used and no events for tag 

### ISSUE THREAD

**Issue by FPG-Github** [unimelb/matrix-controlled-environment#234]
V3 Combined news and events feed shows blank if eventTags used and there are no events for that tag. Fro what I can see if the eventTags option is not in use and the Jason feed is empty (no local news, events or events from event.unimelb) then page displays a "No events found" message (see left browser in screen grab) - but if tagging is used it just renders a empty content area in the page if there are no events that match the tag (see right screen grab).  
![update v3 - combined listing fails to display no events message when usinfg tag filtering](https://cloud.githubusercontent.com/assets/4566277/22677859/28e618cc-ed4a-11e6-9557-07d4da3c72d8.PNG)

I think in the first case the Json feed is empty (no news or events of any kind) so the processor seems to display the correct message - but in the second case the there are events listed with the Json feed so the processor start to build the display but if there are no events that match the tag then it just returns an empty UL tag.

**Comment by rhyslawry** [comment]
Also does this same behaviour if a News/Events CCT is used in the same page or a sibling tab as a combined listing.
Having this issue with Science in June 2017

**Comment by tomstringer** [comment]
The first instance uses the native 'No results' page from the asset listing. The second instance is as a result of processing by the front-end javascript. The solution here will be to use the javascript to detect if no results are returned and to print the no results message.

**Comment by tomstringer** [comment]
Actually, that's not right 👆

The 'No results' message is displayed via the combined listing JS if there's nothing in the JSON response. In the second instance, there _is_ something in the JSON response, but after the filter is applied, no results appear.

We need to update the combined listing JS to trigger the same 'no results' message if there are no items left after filtering.

**Comment by tomstringer** [comment]
Fix deployed with https://github.com/unimelb/matrix-controlled-environment/commit/a96519f7e94935f27baae1a4b925d5af66017eba

See: http://chemistry.unimelb.edu.au/events/melbourne-university-chemical-society-program
