### ISSUE TITLE
Allow sortable table component to sort by any column on load

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#236]
At the moment our [Sortable Table Component](http://web.unimelb.edu.au/components/tables/#sortable-table) will allow sorting by any column (and with optional data type), however on page load it will always sort by the first column

This can be an issue, as the first column is usually the name/title of a particular object, however it is often more logical to sort these objects by a particular attribute rather than alphabetically.

For example:

http://arts.unimelb.edu.au/scholarships/undergraduate

<img width="1190" alt="screen shot 2017-03-03 at 12 13 36 pm" src="https://cloud.githubusercontent.com/assets/10070570/23534279/e6f9d038-000a-11e7-8cfc-a765846eced2.png">

This page shows all open scholarships open to Undergraduates in the Faculty of Arts and on page load it displays the list of Scholarships alphabetically by name, however due to the time-sensitive nature of Scholarships, it makes more sense to have them sorted primarily by their Closing Date on load so more pertinent items are shown at the top of the list.

This may apply in other cases such as "most recently added" assets, "file size" assets etc. where the name of the asset/object should be shown in the first column as it is a strong identifier and sorting alphabetically doesn't add any extra usability to the list.

**Comment by dkevey** [comment]
Hi @jporich this is actually going to be fixed in the DDS v6.0 release which I am currently testing. Should be available within the next week. Will leave this open until complete. 
https://github.com/unimelb/unimelb-design-system/releases

**Comment by dkevey** [comment]
This is now available in v6.0 just released in MCE http://web.unimelb.edu.au/components/tables/#sortable-table
