### ISSUE TITLE
Change form note display from inline-block to block

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#238]
There looks to be an override in the MCE that causes Squiz form notes to display off to the right of the question instead of underneath.

```
.uomcontent fieldset em.sq-form-question-note {
    display: block;
}
```

See `display: inline-block` example here:
![image](https://cloud.githubusercontent.com/assets/15081925/23844008/9d7132ba-0813-11e7-8f0b-981d7706b1a6.png)

Fixed with `display: block` (which I think is the design system default) here:
![image](https://cloud.githubusercontent.com/assets/15081925/23844033/c855deea-0813-11e7-88d4-475b84b05ead.png)

**Comment by rothenburycam** [comment]
👍

**Comment by dkevey** [comment]
Hey @rhyslawry and @rothenburycam do you have some example URLs that I can use to test please?

**Comment by rhyslawry** [comment]
http://www.unimelb.edu.au/governance/structure/committees/academic-board/appeals/unsatisfactory-progress-appeals/course_unsatisfactory_progress_committee_report

**Comment by dkevey** [comment]
remove css override 
.uomcontent fieldset em.sq-form-question-note {
    display: inline-block;
}

**Comment by dkevey** [comment]
fixed this to display notes in block.
