### ISSUE TITLE
News item should show image on full page

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#25]
Thumbnail image for news item should show on main page. May need to make a switch if image should only be thumbnail and not displayed on page (i.e. if you wanted to have an alternate image in the page content?

Also need some help styling additional images on this page.
![news-banner](https://cloud.githubusercontent.com/assets/1305804/9787740/8e39a1e0-5808-11e5-94e5-4854b6879aec.png)

**Comment by dkevey** [comment]
Just looking at this option again and I think we could look at creating a couple of paint layouts (page templates) for the news assets that could utilise the article layout (similar to pursuit).

**Comment by cigar69** [comment]
the FBE paint layout looks good. plus I like how you see the authors & social media sharing options at the bottom of the page.

http://fbe.unimelb.edu.au/home/newsroom/Changing-childrens-lives

Actually, I like a number of features in the FBE newsroom page ( filter by category)

http://fbe.unimelb.edu.au/home/newsroom

**Comment by jporich** [comment]
The main issue we've got is that there's lots of content which has hard coded in images - so we'll end up with a doubling up of images if we default with an image

I've opened this up for discussion and action in MCE Gen 2 - where we don't have much content at all and we can be a bit freer in changing the structures of our News Items. 

I'm going to close this item for now as it's pretty much not actionable with our current number of assets across the university - however I've kicked off discussion on how we might do this with a "fresh slate"
