### ISSUE TITLE
Image Listing Content Template - get thumbnails working correctly

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#251]
Need to ensure thumbnails are correctly called for each image size option. Didn't quite get it working correctly. Only affects page size on load, not visual image. 

https://resources.web.unimelb.edu.au/controlled-environment/content-templates/image-listing

**Comment by woowoowoo** [comment]
This also affects image gallery content template, but I'll raise a separate bug for that, as it's separate assets. Technique will be similar though, so keep an eye on #311

**Comment by jporich** [comment]
Item has been fixed as part of merge #314
