### ISSUE TITLE
Events listing component has limited history

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#258]
It appears that events older than a certain timeframe (i.e. 24 months) do not appear in event listings. It would be great to have the option to choose longer timeframes in the component (i.e. list events only from the last two years/list all events).

**Comment by dkevey** [comment]
This is correct. Past events are set to show 720 days in the past. This was carefully considered to do low traffic to these assets and potential performance issues. Personally I fail to see merit in showing past events longer than is. Do you have a particular case to put forward?

**Comment by rothenburycam** [comment]
Thanks @dkevey - appreciate those considerations. I've logged this on behalf of my manager, Michele Burder.

In this instance, she's building a research group website  - for research groups, being able to display a full history of events allows them to display the full extent of their output, which helps strengthen their public profile.

**Comment by dkevey** [comment]
If you have examples that you can link here that would be helpful. My understanding of research outputs are that they are generally captured and presented in research papers rather than historical records websites or events. We probably need more context around wether or not this is required for research projects that are active with funding and can be supported longer term. Websites in MCE that are not up to date and current are generally archived under the Records Management Policy (MPF1106).

**Comment by rothenburycam** [comment]
Here's an example: http://cms.unimelb.edu.au/controlled-environment/acahuch/

Yes, you're right about research outputs - Michele's point is that being able to display the full history of events is a way of documenting additional output from a project that wouldn't necessarily be in a research paper (i.e. lectures, workshops, presentations, exhibitions, etc).

**Comment by rothenburycam** [comment]
The solution Michele went with here was to add a page asset listing component at the bottom where old events can be shown historically. I think this is a fine way of dealing with it, as it will be a very small group of websites who would want to list events this old.

https://cms.unimelb.edu.au/controlled-environment/acahuch/#events

**Comment by dkevey** [comment]
fixed this in new Events listing content template https://resources.web.unimelb.edu.au/controlled-environment/content-templates/events-listing no further action required
