### ISSUE TITLE
Allow videos on the Text - Two Columns component

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/matrix-controlled-environment#262]
Related to #252 :

_Many many people use videos in conjunction with a `<div class="half">` - having a video in one column and text in the other. They currently have to hard-code this._

#### Request: Allow videos on the Text - Two Columns component as well, instead of just images.

Extra fields:
*Media type*: `Image`, `Video`, (Default: `Image`)
*Video URL*:  `Text field`

Component would insert the video with the correct markup if the Media type: `Video` was chosen.
Otherwise it would use the image chosen in the `Select an image` field like normal

This could theoretically solve two problems at once

![image](https://cloud.githubusercontent.com/assets/15081925/26381815/c8f84ccc-406a-11e7-8732-7c9cd8e3e598.png)
![image](https://cloud.githubusercontent.com/assets/15081925/26381889/4258f6a2-406b-11e7-9faa-a18953fec61d.png)

**Comment by dkevey** [comment]
Hey @rhyslawry this is a good idea - do you have any example sites currently do this I could look at please? I could look at adding a link asset or something similar.

**Comment by woowoowoo** [comment]
Videos are usually coded as an embed (raw html), so really this would end up allowing the insertion of embed code from just about anywhere - twitter, FB, Vimeo etc.

I'm actually using this layout on the new/draft home page - not that I necessarily think it's great, just that I'm mimicking what's currently on the home page http://cms.unimelb.edu.au/dshome/

Another minor consideration is that Axel is talking about a method for 'lazy loading' video embeds with an image placeholder the way the first video is set up on the current home page. eg: you click the image, javascript replaces the image with the video embed, which then starts to play. Tricky, and can probably be ignored as it's a technique focussed on high traffic pages.

**Comment by dkevey** [comment]
@rhyslawry and @woowoowoo we have a request here for a Video Content Template https://github.com/unimelb/matrix-controlled-environment/issues/252 I think this would be best to address videos here as they have particular requirements. I'm going to close this request - if you could please add in requirements and example URL's into issue 252 then we can address them there
