### ISSUE TITLE
Logo listing spacing problem in firefox with srcset

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#264]
Obscure bug.

Using logo-listing with srcset.
    `<img alt="Association of Pacific Rim Universities" src="./?a=2365209" srcset="./?a=2365209 1x, ./?a=2365209:v1$ 2x" />`

Works fine as far as displaying the appropriate image, but in Firefox the spacing seems to adjust based on the pixel dimensions of the 2x version. See screen grab - Chrome above, Firefox below.

<img width="728" alt="screen shot 2017-05-24 at 2 28 22 pm" src="https://cloud.githubusercontent.com/assets/848310/26387081/3464168a-408e-11e7-9704-5d8173de3cf7.png">

**Comment by dkevey** [comment]
sorry what was the page URL?

**Comment by woowoowoo** [comment]
That's on my dev home page, but I'm mucking about with it all the time, so it'll be there one minute and gone the next. http://cms.unimelb.edu.au/dshome/

**Comment by woowoowoo** [comment]
Oh dear, just dawned on me that I posted this issue in the wrong repository - should be in the Design System. D'oh!
