### ISSUE TITLE
Harmonise title attributes and metadata

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#265]
When setting a custom title attribute, I'd expect to see this reflected in all places that display a title attribute: The title tag, meta title, og:title, and twitter:title

Currently, the custom title attribute %globals_asset_metadata_Title% is only displayed in the title tag, the others still refer to %globals_asset_name%

Can we use %globals_asset_metadata_Title% to populate all instances of a title attribute?

**Comment by dkevey** [comment]
have updated Global head so that %globals_asset_metadata_Title% is displayed in og:title, and twitter:title
