### ISSUE TITLE
Cache busting css is (unsurprisingly) busting cache

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#266]
The technique of adding a query string to the URL of the uom-mce.css is designed to 'bust' caches, which it does very effectively, and that's great. Unfortunately, at the performance end, cache busting is undesirable.
If the file is not frequently changed, it should be cached, and quite aggressively.

Is there a technique we can use to cache when we need to and only bust when we have to?

**Comment by rhyslawry** [comment]
Maybe one of these techniques will be suitable for us?

https://css-tricks.com/strategies-for-cache-busting-css/

**Comment by woowoowoo** [comment]
Yeah, unfortunately, we don't have access to most of those techniques, partly because Matrix is a bit of a black box, but also because we rely on the squiz edge CDN. Query strings, and file names are pretty much the only tools we have. But maybe we can invoke them in smart ways.

I wonder if the query string could be invoked only when we need it - when an update is made, or when there's dev going on.

It's not a big issue, doesn't need to be resolved urgently, just a niggle.

**Comment by tomstringer** [comment]
Some interesting discussion here: https://squizmap.squiz.net/matrix/5628 and https://squizmap.squiz.net/matrix/5703 (if you have access?

**Comment by dkevey** [comment]
I've removed this for now as generally the override file doesn't get updated that often. Will need to /_recache pages to get the updated version.
