### ISSUE TITLE
Force "Text - figure floating" container to clear

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#268]
The containers in Text - figure floating do not wrap around the image, or clear containers before them. Container should have `clear:both;` applied to force it below its predecessor. 

![screen shot 2017-06-01 at 3 35 53 pm](https://cloud.githubusercontent.com/assets/11714609/26665918/20b7bf62-46e0-11e7-81be-fa11e9a1f3c1.png)

**Comment by dkevey** [comment]
@rothenburycam can you please send through URLS and browser you are using - I can't replicate this.

**Comment by rothenburycam** [comment]
@dkevey I can't link you to an example as I opted not to use the content containers for now. If you just stack two of the `Text - figure floating` above eachother with the default settings, you'll be able to replicate the above screenshots.

**Comment by dkevey** [comment]
It looks like you haven't added any content to these containers. They need content to work correctly as per the instructions here: https://resources.web.unimelb.edu.au/controlled-environment/content-templates/figures-floating they are not meant for use as just image positioning. 

I'll close this off for now. Feel free to re-open it if you have examples that I can look at.

**Comment by rothenburycam** [comment]
Ah yes, ignore this. I just realised that the two column component does what I want.

https://resources.web.unimelb.edu.au/controlled-environment/content-templates/two-columns
