### ISSUE TITLE
Filtered listing page / Green tiles  / mobile render ???

### ISSUE THREAD

**Issue by cigar69** [unimelb/matrix-controlled-environment#271]
#### Expected behaviour
The Filtered listing page, listing research projects ( green boxes)  in a mobile portrait mode, rendering to the  green boxes  and containing the content of the boxes  without any overlapping text in the white space 

#### Actual behaviour
The Filtered listing page, listing research projects ( green boxes)  in a mobile portrait mode, renders to the user misaligned green boxes   with overlapping text (screen shots attached).

![screenshot_20170613-231135](https://user-images.githubusercontent.com/4565925/27113215-f33caf4c-50fe-11e7-9694-3f611af208ae.png)
![screenshot_20170613-231143](https://user-images.githubusercontent.com/4565925/27113214-f33b9472-50fe-11e7-8258-f74bf7471c76.png)
![screenshot_20170613-231228](https://user-images.githubusercontent.com/4565925/27113213-f33b0160-50fe-11e7-9cd3-8b8da6c05152.png)
![screenshot_20170613-231244](https://user-images.githubusercontent.com/4565925/27113216-f33da6e0-50fe-11e7-8908-0c88f9ecaa94.png)

#### Steps to reproduce
Mobile
Portrait mode
example URL : http://medicine.unimelb.edu.au/research-groups/medicine-and-radiology-research/austin-hospital/

**Comment by dkevey** [comment]
Hi @cigar69 sorry can you please post on the Design System github under this issue https://github.com/unimelb/unimelb-design-system/issues/807

**Comment by dkevey** [comment]
closing this one as it has been added to DDS
