### ISSUE TITLE
Allow choice of image varieties for Text - Two Column template

### ISSUE THREAD

**Issue by timpw** [unimelb/matrix-controlled-environment#276]
#### Expected behaviour
When using the Text - Two Columns template layout, could we make it so users are able to select the automatically resized "varieties" squiz generates for large images? (banner, large, medium, thumbnail - the ones with :v1, :v2, etc added to the end of their asset numbers that sit under the original asset).

#### Actual behaviour
The template currently only allows for selection of the original parent asset. This means if you want to use an image in the two column layout and as a banner on another page, you have to upload two versions - one large enough for the banner and one resized for the two column layout. Otherwise you have to load a banner sized image into the two column layout space.

![screen shot 2017-07-04 at 10 24 59 am](https://user-images.githubusercontent.com/21092709/27810886-192702b2-60a3-11e7-8658-33379e732bbf.png)
_(note that the resized versions are greyed out and cannot be selected)_

**Comment by dkevey** [comment]
Hi @timpw I was hoping to tackle use of image varieties within the content templates themselves, but I can see the benefit of setting 2 different types of images - so have now allowed for use of image varieties on **Text - Two Column** and **Text - Figures Floating**
