### ISSUE TITLE
Heading tag in Two Column layout doesn't match design system

### ISSUE THREAD

**Issue by timpw** [unimelb/matrix-controlled-environment#278]
#### Expected behaviour
In the design system, the two column text layout uses an `<h1>` tag for the heading. As seen on the components page:
https://web.unimelb.edu.au/components/text/#two-columns
![screen shot 2017-07-12 at 12 47 57 pm](https://user-images.githubusercontent.com/21092709/28099531-6d482f5c-6700-11e7-9b3b-a2b6291c1767.png)

#### Actual behaviour
When using the new Text - Two Columns template in the MCE however, the heading has been set up using an `<h2>` tag. As seen in the screenshot below:
![screen shot 2017-07-12 at 12 51 08 pm](https://user-images.githubusercontent.com/21092709/28099597-d2b5345c-6700-11e7-9947-65ae6866bd32.png)

#### Steps to reproduce
This happens on all pages using the template. Is it possible to change the `<h2>` tag to an `<h1>`, so that components are consistent across other sites as well (such as bespoke sites)? Cheers.

**Comment by dkevey** [comment]
Hi @timpw - we've had a few discussions around headings and how we can use them consistently in Content Templates. According to the WCAG and WebAIM guidelines, <h1> are generally only used once on the page (i.e the page title) so use of <h2> is semantically correct in this instance. http://webaim.org/techniques/semanticstructure 

However, we all agree the the headings in generally aren't styled that well (see github DDS issue https://github.com/unimelb/unimelb-design-system/issues/904 ).  I believe the new designs have addressed this, but I'll leave this open for now to discuss with our new designers.

**Comment by dkevey** [comment]
Closing this off for now as DDS is incorrect and I'm not sure it will get updated with the new DDS coming.
