### ISSUE TITLE
News Listing Component only works with Link Assets when using "Block" listing style

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#280]
External News Items are usually posted with _Link Assets_ in News Listings. 

This works fine when using the "block listing" layout, however using "News Listing" or "News Listing Dense" has the assets in the listing linking to the _Link Asset_ itself (rather than the _Link Asset_'s 'link value' on the Details screen)

Should be a quick fix by changing those layouts to utilise a new Asset Type for Links that makes use of %link_url% rather than what is there (maybe currently something like href="./?a=%asset_assetid%" or href="%asset_url%")

**Comment by dkevey** [comment]
@jporich can you please include a URL for the page you are using this on? Makes it easier to test.

**Comment by jporich** [comment]
Whoops! Rushing that one:

http://biomedicalsciences.unimelb.edu.au/departments/microbiology-Immunology/engage/bo-and-merang/news-and-events/

Three link assets underneath that one!

**Comment by dkevey** [comment]
that was a good pickup @jporich - can you please double check this is now working as expected? http://biomedicalsciences.unimelb.edu.au/departments/microbiology-Immunology/engage/bo-and-merang/news-and-events/_recache
