### ISSUE TITLE
Matrix / TAG.Project (Id: #1624283) - request for new status option in drop-down

### ISSUE THREAD

**Issue by cigar69** [unimelb/matrix-controlled-environment#284]
#### Expected behaviour

MDHS is creating a repository of `future' Graduate Research, PhD & Honours projects. Currently the Page control (Id: #1385714)  Metadata-schema includes TAG.Project (Id: #1624283). The available status options from the drop-down are `Current' & ` Completed'. We would like to maximize this metadata field by having the option `Future' added to the status drop-down.

example pages can found under Student Research Project (Id: #2423613)

**Comment by dkevey** [comment]
@cigar69 can you please post a URL as well that I can test against

**Comment by cigar69** [comment]
Donna,

see URL below

http://mdhs.unimelb.edu.au/research/2018-research-project-respository/melbourne-medical-school/student-research-project/understanding-emotional-information-processing-in-bipolar-disorder/_recache

![image](https://user-images.githubusercontent.com/4565925/28703099-083fa12e-73a5-11e7-81fa-52785590cd36.png)

**Comment by dkevey** [comment]
@cigar69 have added *Future* tag http://mdhs.unimelb.edu.au/research/2018-research-project-respository/melbourne-medical-school/student-research-project/understanding-emotional-information-processing-in-bipolar-disorder/_recache
