### ISSUE TITLE
Pathfinder Content Template not fetching Button Text

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#287]
#### Expected behaviour
When adding a pathfinder, the button text should fetch a default value from the target page: "Defaults to target asset metadata field 'Button Text'."

#### Actual behaviour
Does not fetch button text from target page, just inserts default text "Read More"

#### Steps to reproduce
I was changing the CMS training documents from using an accordion example, to using a pathfinder example, and had set up asset #1538180 (the downloadable maps page) as an example target. The Button text for that asset is "View the maps".

**Comment by dkevey** [comment]
This was changed a while ago so that if the *Button Text* field was empty then it would use *Read more* - have changed the instructions to reflect this and also changed if empty to use *View*. Sorry for the confusion.
