### ISSUE TITLE
Improve main menu

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#29]
At the moment the menu is set to not show Link Type 2. This means all pages show in the menu unless you change link type. 

Breadcrumbs is set to show link type 2. 

Need a way to be able to set only main menu (with either link type 1 or link type 2) - turn off link type 2 in breadcrumbs.  

![image](https://cloud.githubusercontent.com/assets/1305804/9985008/028dee46-6067-11e5-92b3-70878c977c03.png)

![image](https://cloud.githubusercontent.com/assets/1305804/9985013/136afd58-6067-11e5-8df8-b34e738b8efe.png)

![image](https://cloud.githubusercontent.com/assets/1305804/9985018/1a60dd62-6067-11e5-9c12-90e3943acea4.png)

![image](https://cloud.githubusercontent.com/assets/1305804/9985021/286e99b2-6067-11e5-8568-85a2c56ba70a.png)

**Comment by yevek** [comment]
Have logged issue with Design Team to have div.inner behaviour modified https://github.com/marcom-unimelb/unimelb-design-system/issues/773

Once this is solved, have an option for a curated menu in place.

**Comment by dkevey** [comment]
needed for new home page

**Comment by woowoowoo** [comment]
The new local menu does not display pages ((under construction)) as the old one did.
Particularly problematic for sites under development, or in training, as there's no way to preview or use the navigation.
Can we please get the behaviour restored to include Under Construction assets.

**Comment by dkevey** [comment]
this is now complete https://resources.web.unimelb.edu.au/controlled-environment/help-guides/managing-your-local-site-menu
