### ISSUE TITLE
Image variations in combined news/events

### ISSUE THREAD

**Issue by tomstringer** [unimelb/matrix-controlled-environment#293]
#### Expected behaviour
Where an image has smaller, child variations, use these when outputting combined news/events listings.

#### Actual behaviour
Currently outputting full-size image instead.

#### Steps to reproduce
http://science.unimelb.edu.au/news/welcome-to-the-jungle

**Comment by jporich** [comment]
This also seems to persist across Content Templates also
- Page Listing
- Two Column layout
- Text with Figure
- etc...

Potentially a fix that could be implemented across several items.

**Comment by jporich** [comment]
Fixed - for details see Thumbnail fix for Combined News/Events Listing #315 

Keyword combo for selecting image variety with fallback is:
`%begin_asset_thumbnail_v_medium_width^eq:600%%asset_thumbnail_v_medium_url%%else_assset%%asset_thumbnail_url%%end_assset%`
