### ISSUE TITLE
Pathfinder no longer links to Custom Form

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#295]
A Pathfinder I had created using the Container template was set up to link to a Custom Form asset. 

#### Expected behaviour
When implemented, it worked fine, and users could link through to a request form.

#### Actual behaviour
Custom form assets are no longer an eligible type. My Pathfinder would not work, and I've had to refactor the page.

If there is no reason for this exclusion, I think the functionality should be restored.

**Comment by dkevey** [comment]
completed and documentation updated https://github.com/unimelb/web-templates-2017/issues
