### ISSUE TITLE
Nesting contact page into a homepage tab causes embedded maps to display incorrectly

### ISSUE THREAD

**Issue by timpw** [unimelb/matrix-controlled-environment#296]
#### Expected behaviour
Embedded maps should display consistently on all page types.

#### Actual behaviour
I've embedded a map on a contact page for a site. The page is one that is then pulled into a tab on the website's homepage via nesting content.

On the original page, the map displays correctly (it should show the MSD building):
![screencapture-cms-unimelb-edu-au-controlled-environment-bowerstudio-contact-us-_nocache-1502952587616](https://user-images.githubusercontent.com/21092709/29399493-d1a80570-836c-11e7-8d79-3ec1fde7fa6f.png)
https://cms.unimelb.edu.au/controlled-environment/bowerstudio/contact-us

This contact page is to be included on a tab of the site homepage, so the content has been nested into a page under the home page. At this stage, it still works correctly:
![screencapture-cms-unimelb-edu-au-controlled-environment-bowerstudio-home-contact-us-1502952643175](https://user-images.githubusercontent.com/21092709/29399492-d1a76c1e-836c-11e7-867f-ed9a15596662.png)
https://cms.unimelb.edu.au/controlled-environment/bowerstudio/home/contact-us

But, when the home page is rendered with tabs, the map becomes offset somehow. It's still close to where it needs to be, but it not displaying the correct part of the map
![screencapture-cms-unimelb-edu-au-controlled-environment-bowerstudio-1502952668114](https://user-images.githubusercontent.com/21092709/29399494-d1a8575a-836c-11e7-886c-fb545961e2c9.png)
https://cms.unimelb.edu.au/controlled-environment/bowerstudio#contact-us

#### Steps to reproduce
I've set up the map on the original page using the design system specifications here: https://web.unimelb.edu.au/components/maps/ This has been created in the Contact Us page (#2450143). Then the contents of this page are nested into a child asset of the home page as per standard setup (#2450143). On both these pages the map displays correctly. However, when the home page (#2450127) is generated using the child pages as tabs, the area the map displays becomes offset. I'm not sure if this is a MCE or design system issue, but since it seems to work in the original pages and only stop working when the home page is generated, I think it might be something Squiz is doing.

**Comment by timpw** [comment]
I've just discovered that if you reload the home page when on the contact us tab, it will display the map correctly. But if you click on another tab and then back to the contact us tab, the map is wrong again.

**Comment by woowoowoo** [comment]
There are some strange problems with embedding maps in hidden elements.

Aside from that, though. Please don't embed maps on home pages. Each load registers a map view (and cost), and the vast majority of visitors never use, or even view the map. Link to the map page instead. 

Andrew Harris
email: andrew@woowoowoo.com
twitter: @woowoowoo

**Comment by timpw** [comment]
Ok. That makes sense, and I'm happy to change it.

FYI - it might be worth updating the default pages created for new shell sites in that case as well then. The current set up that is provided includes a "contact us" tab on the homepage with an embedded map, just using generic Unimelb contact/location details. All I did was update them to specific contact information for this centre.

**Comment by woowoowoo** [comment]
Good point - thank you for the suggestion. A new shell site is in the works and this will definitely be implemented.
