### ISSUE TITLE
Allow option for Introductory text to display under tabs

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#300]
#### Expected behaviour
Introductory text metadata should be able to be displayed under tabs if required. It would be great to have an additional metadata field that allows you to stipulate if the intro metadata should display under tabs.

#### Actual behaviour
Tabbed component doesn't render the introductory text on pages nested under tabs - it only appears on the page when viewed as a single standalone page.

The only way to have intro text appear is to have a `section.lead` in the page, which can cause issues for page listings or result in duplicate content.

#### Steps to reproduce

1. Create a page using tabbed navigation
2. Create a subpage
3. Add introductory metadata to the subpage, or nest a page with metadata attached to it.

![2017-09-19 14_08_00](https://user-images.githubusercontent.com/11714609/30575479-691c578a-9d44-11e7-9b5d-91a800055d69.gif)

Example: https://cms.unimelb.edu.au/controlled-environment/msd/#about

**Comment by dkevey** [comment]
Hey, sorry we won't be fixing this one. If you want the text to display in both places you will need to add it to the page content area instead of the metadata field. That way it will display in both places.
