### ISSUE TITLE
Not able to edit Redirect Assets with Edit+

### ISSUE THREAD

**Issue by FPG-Github** [unimelb/matrix-controlled-environment#304]
#### Expected behaviour
Edit+ users should be able to edit Redirect Assets

#### Actual behaviour
Editors are unable to access Redirect Assets with Edit+. If they try the screen stalls on the blue spinning loading icon until it eventually times out and displays a  GET or Post error.  

#### Steps to reproduce
Try to access a redirect asset with /_edit or try selecting it for editing from within Edit+ via the Asset Finder.
Note this only occurs for Redirect assets within the MCE, so directly related to the local setup - most likely EasyEdit.plugins.customMessage (Id: #2394079) or metadataToggle.json (Id: #2462057) as you briefly see these attempting to be loaded:
![edit on page redirects](https://user-images.githubusercontent.com/4566277/31754397-05b75dbe-b4e3-11e7-8a4c-075afe0e9980.png)
 
This issue has been reported to Squiz .

**Comment by dkevey** [comment]
Squiz report this is a issue with our version of Matrix which is fixed in 5.4.21. It's been reported here - https://squizmap.squiz.net/matrix/10728

**Comment by dkevey** [comment]
Squiz have applied fix so redirect assets can now be edited in MCE.
