### ISSUE TITLE
Allow for "open in new tab" functionality when using Redirect Page asset.

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#306]
#### Expected behaviour
The Redirect Page asset features a "New Window?" option in the bottom of it's details screen:
<img width="765" alt="screen shot 2017-11-09 at 9 50 00 am" src="https://user-images.githubusercontent.com/10070570/32579071-bf7069fc-c533-11e7-8559-fe8f4e9830a3.png">

When using a Redirect Page in a Page Listing, Hero Listing, Navigational Listing etc. it would make sense to apply a `target="_blank"` attribute to links if they are of Redirect Page type and have that attribute selected on them.

**Note: This should be only used for navigationally _exiting_ current website structures**

This mostly helps with things like payment portals and external links. E.g. on the following page:

http://arts.unimelb.edu.au/engage/extended-and-community-learning-programs/short-courses-and-masterclasses

Several links go to payment portals and can be confusing for users who wish to keep viewing other short courses.

#### Actual behaviour
This Attribute currently does nothing when selected

#### Steps to reproduce
Make a Redirect Page asset a child of a Page Listing - select an external website as a it's URL to redirect to - set "New Window?" to "Yes" and note that there is no effective change in behaviour or attributes of the link

**Comment by dkevey** [comment]
Hey @jporich just been chatting with the team about this and the consensus is that all links should open in the same window. This allows users to use the back button (as many do) and if they wanted to open the link in a new window they have the option to right click > open in new window. The exception is opening documents in new windows.
