### ISSUE TITLE
Image Gallery content template should use thumbnails

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#311]
#### Expected behaviour
Image Gallery component should use the thumbnail version in grid view.

#### Actual behaviour
Image gallery container template is loading full resolution version of the file when using a folder as a source.

This is related to #251 , but the assets are separate. Technique to fix will likely be similar.

**Comment by jporich** [comment]
Fixed, see latest pull request:

https://github.com/unimelb/matrix-controlled-environment/pull/312
