### ISSUE TITLE
Can't edit page?

### ISSUE THREAD

**Issue by datakid** [unimelb/matrix-controlled-environment#318]
#### Expected behaviour
that I can add _edit to the end of the page https://research.unimelb.edu.au/infrastructure/research-platform-services/ and remove the red text.

#### Actual behaviour

It appears empty. No obvious way to remove the announcement. See this image

![screenshot from 2019-02-07 14-34-24](https://user-images.githubusercontent.com/97304/52389206-6eb96800-2ae6-11e9-8a34-31ef31d50bf5.png)

#### Steps to reproduce
Login as me, add _edit on the end, go to content.

**Comment by woowoowoo** [comment]
Lachlan,
the page you should be editing is: https://research.unimelb.edu.au/infrastructure/research-platform-services/services
It is nested in the other page using tabbed navigation.
