### ISSUE TITLE
Meta menu

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#82]
We need a way of enabling the Meta menu.

![screen shot 2016-03-04 at 3 21 33 pm](https://cloud.githubusercontent.com/assets/848310/13517973/2a422d7a-e21d-11e5-9169-be7fbd0de490.png)
![screen shot 2016-03-04 at 3 23 53 pm](https://cloud.githubusercontent.com/assets/848310/13517982/332dd5b0-e21d-11e5-80f1-f0cb2ae6e016.png)

**Comment by yevek** [comment]
Revisiting this idea of **meta menu** + **curated hamburger menu**. Have logged issue with Design Team to have div.inner behaviour modified https://github.com/marcom-unimelb/unimelb-design-system/issues/773

RE: meta menu: 

- should this be custom to each site?
- should there be a default menu if none selected OR
- should this just be general menu for whole of UoM?

**Comment by dkevey** [comment]
have an option for this, just waiting for https://github.com/unimelb/unimelb-design-system/issues/773 to be addressed
